version: '3'

services:
  server:
    image: server
    command: sh -c "npm run watch"
    volumes:
      - ./server/src:/server/src
    environment:
      - DB_HOST
      - DB_PORT
      - DB_DIALECT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
    ports:
      - '8000:8000'
    depends_on:
      - mysql
  mysql:
    image: mysql
    ports:
      - '8001:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - './db:/var/lib/mysql'